### ISSUE TITLE
Running inference with individual seqs

### ISSUE THREAD

**Issue by mchowdh200** [puar-playground/AsMac#1]
Hi, I just read your preprint and I think the ideas presented are really neat.  I'm able to run the demo but am having trouble running inference on a single input (ie run on one sequence to see the embedding).

Here's how I've been running it so far

```
from AsMac_model import AsMac
import torch
torch.set_printoptions(profile="full")
import numpy as np
np.set_printoptions(precision=10)

# define model
embed_dim = 300 # number of kernel sequences
kernel_size = 20 # kernel length

# initialize EINN object
net = AsMac(4, embed_dim, kernel_size)

# load model weights
net_state_dict = torch.load('model/final.pt')
net.load_state_dict(net_state_dict)
x = net.test_embed(b"seq left out for this example")
```
running this script gives the following Error (truncated to show relevant parts of error)

```
File "_softnw.pyx", line 87, in _softnw.embed_value_fast
    def embed_value_fast(double[:, :] seq, double[:, :] weight, double gap):
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
BufferError: Object is not writable.
```
A brief search online leads me to believe that cython is involved here (passing bytes object specifically), but perhaps this is caused by improper usage of the model.  Let me know if I'm using the model correctly, or if there is some other possible cause for these errors.

Thanks,
Murad

**Comment by puar-playground** [comment]
Hi Murad:

In short, the sequences should be saved as a list of strings. Then you need to transform them into one-hot sequences. The model will compute embeddings one-by-one. 

I have provided a script "embedding.py" to show you how to get embeddings for sequences.

Best, 
Jian
