### ISSUE TITLE
train fragmented sequences

### ISSUE THREAD

**Issue by jianshu93** [puar-playground/AsMac#2]
Hello Team,

This is a very interesting idea. I tried the training code and it ran successfully. My question is: can the model also work for fragmented sequences, e.g. a genome of an organism (due to technical issues, it is not a linear but up to a hundred or so fragments), or we need to manually put them together to have a single piece (knowing they are not continuous). Normally, marker genes will be only several kb or less but a genome can be 10^6 bps, will be more training take much longer?

Thanks,

Jianshu

**Comment by puar-playground** [comment]
Hi:

I'm glad you liked it. I believe the proposed neural network structure could be generalized for local comparisons, which is more suitable for overlapping reads and contigs. Unfortunately, the current implementation can not be applied to ultra-long sequences. The main reason is the approximate string matching required in each iteration will be very time-consuming. And more parameters will be required. Thus, the training for thousand times long sequences might take a hundred thousand times longer per iteration. However, using heuristics to find the best matches or using large-scale parallelization might solve this problem.

Jian

**Comment by jianshu93** [comment]
Hello Jian,

Thanks for the response. I am asking the question because I wanted to know whether this idea could be applied to calculated identity between 2 genomes, not just 2 marker genes. It is not possible to align 2 10^6 genomes to calculate identity, but fragment it into 1-3kb pieces and then find the best hit in another and use identity with that best hit to calculated average identity, so for each fragment we will have an identity and then average it (even so it is still very expensive).  Finding best hit in the genomic case will be much more complicated but what about avoiding string match, using something like MinHash (based on shared kmers).


Thanks,

Jianshu

**Comment by puar-playground** [comment]
From my previous experience, a small number of insertions/deletions contribute negligibly to sequence similarity in genome-level comparisons. So there is no need to use operations like approximate string matching.

I think the idea you said is feasible, and the method of using kmer can effectively improve the calculation efficiency. A series of similar methods have been proposed, I hope you can get more inspiration from them.
